# Generated by Django 4.0.4 on 2022-06-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='likers', to='network.post'),
        ),
    ]
